version: 1.0.{build}-{branch}
image: Visual Studio 2019

install:
  - git submodule update --init --recursive
  - cmake.exe -H. -Bbuild -T v142

build_script:
  - msbuild.exe build/aacgain.sln -t:aacgain -p:Configuration=Release

test_script:
  - C:\Python38\python.exe tests\test.py build\aacgain\Release\aacgain.exe

before_deploy:
  - cmake.exe --build build --target install
  - copy "C:\Program Files\aacgain\aacgain.exe" aacgain-2.0.0-windows-amd64.exe

deploy:
  - provider: GitHub
    artifact: aacgain-*.exe
    draft: false
    auth_token:
      secure: efNJ/b8h3rXqahkooeZS+I4N/1DJIOgg8ek1X/sjKC+8f0Vgs+9Yy+vrR6f1t96X
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
